

if(FALSE){
    
    x <- rbind(
        rGaussian(50,mu = c(-1.5,1.5),Sigma = matrix(c(0.1,0.03,0.03,0.1),2,2)),
        rGaussian(60,mu = c(-1.5,-1.5),Sigma = matrix(c(0.8,0.5,0.5,0.8),2,2)),
        rGaussian(70,mu = c(1.5,1.5),Sigma = matrix(c(0.3,0.05,0.05,0.3),2,2)),
        rGaussian(50,mu = c(1.5,-1.5),Sigma = matrix(c(0.5,-0.08,-0.08,0.5),2,2))
    )
    mmData <- x
    save(mmData,file = "~/github/bbricks/data/mmData.RData")
    
    set.seed(1)
    j <- as.integer(round(runif(30,40,50)))
    PIs <- rDir(30,c(1,2,3,1))
    Xs <- list(
        list(n=1,mu = c(-1.5,1.5),Sigma = matrix(c(0.1,0.03,0.03,0.1),2,2)),
        list(n=1,mu = c(-1.5,-1.5),Sigma = matrix(c(0.8,0.5,0.5,0.8),2,2)),
        list(n=1,mu = c(1.5,1.5),Sigma = matrix(c(0.3,0.05,0.05,0.3),2,2)),
        list(n=1,mu = c(1.5,-1.5),Sigma = matrix(c(0.5,-0.08,-0.08,0.5),2,2))
    )
    x <- do.call("rbind",lapply(1L:30L,function(i){
        out <- matrix(0,nrow = j[i],ncol = 2L)
        for(r in 1:nrow(out)){
            classLabel <- rCategorical(1,PIs[i,])
            out[r,] <- do.call("rGaussian",Xs[[classLabel]])
        }
        out
    }))
    js <- rep(1L:30,times=j)
    mmhData <- list(x=x,groupLabel=js)
    save(mmhData,file = "~/github/bbricks/data/mmhData.RData")
    
    set.seed(1)
    J <- as.integer(round(runif(30,40,50)))
    PIs <- rbind(rDir(10,c(1,2,3,1)),
                 rDir(20,c(3,2,1,3)))
    Xs <- list(
        list(n=1,mu = c(-1.5,1.5),Sigma = matrix(c(0.1,0.03,0.03,0.1),2,2)),
        list(n=1,mu = c(-1.5,-1.5),Sigma = matrix(c(0.8,0.5,0.5,0.8),2,2)),
        list(n=1,mu = c(1.5,1.5),Sigma = matrix(c(0.3,0.05,0.05,0.3),2,2)),
        list(n=1,mu = c(1.5,-1.5),Sigma = matrix(c(0.5,-0.08,-0.08,0.5),2,2))
    )
    x <- do.call("rbind",lapply(1L:30L,function(i){
        out <- matrix(0,nrow = J[i],ncol = 2L)
        for(r in 1:nrow(out)){
            out[r,] <- do.call("rGaussian",Xs[[rCategorical(1,PIs[i,])]])
        }
        out
    }))
    js <- rep(c(1L:10L,1L:20L),times=J)
    ms <- rep(2L,nrow(x))
    ms[1:sum(J[1:10])] <- 1L
    mmhhData <- list(x=x,groupLabel=ms,subGroupLabel=js)
    save(mmhhData,file = "~/github/bbricks/data/mmhhData.RData")
    
    X <- matrix(1:100,ncol=1)
    x <- rnorm(100,sd=5)+ as.vector(X)*0.3
    lrData <- list(x=x,X=X)
    save(lrData,file = "~/github/bbricks/data/lrData.RData")

    farmads <- readLines("~/Dropbox (Mendix)/tmp/Mendix/UserProfiling/topic/farm-ads")
    farmads <- tolower(farmads)
    farmads <- gsub("[0-9]","",farmads)
    farmads <- gsub("[a-z]+-[a-z]+","",farmads)
    farmads <- gsub("[^a-z ]","",farmads)
    library(cld3)                           #detect language
    idx <- sapply(farmads,detect_language,simplify = TRUE,USE.NAMES = FALSE)=="en"
    farmads <- farmads[idx %in% TRUE]
    while(any(grepl("( [a-z]{2} )|( [a-z]{1} )|(^[a-z]{2} )|( [a-z]{2}$)|(^[a-z]{1} )|( [a-z]{1}$)",farmads)))
        farmads <- gsub("( [a-z]{2} )|( [a-z]{1} )|(^[a-z]{2} )|( [a-z]{2}$)|(^[a-z]{1} )|( [a-z]{1}$)"," ",farmads)
    farmads <- gsub(" +"," ",farmads)
    farmads <- gsub("(^ )|( $)","",farmads)
    set.seed(1)
    x <- strsplit(sample(farmads,400),split = " ")
    x <- sapply(x,function(l){unique(l)},simplify = FALSE,USE.NAMES = FALSE)
    removeWords <- table(unlist(x))
    removeWords <- names(removeWords[removeWords<10 | removeWords>50])
    x <- sapply(x,function(l){
        setdiff(l,removeWords)
    })
    x <- x[sapply(x,length,simplify = TRUE,USE.NAMES = FALSE)!=0]
    js <- rep(1L:length(x),times=sapply(x,length,simplify = TRUE,USE.NAMES = FALSE))
    x <- unlist(x)
    farmadsData <- list(word=x,document=js)
    save(farmadsData,file = "~/github/bbricks/data/farmadsData.RData")
    
    X <- matrix(c(
        0, 1083,
        0, 855,
        2, 3461,
        0, 657,
        1, 1208,
        1, 1025,
        0, 527,
        2, 1668,
        1, 583,
        3, 582,
        0, 917,
        1, 857,
        1, 680,
        1, 917,
        54, 53637,
        0, 874,
        0, 395,
        1, 581,
        3, 588,
        0, 383),
        ncol = 2, byrow = TRUE)
    cancerData <- apply(X,1,function(l){
        rep(c("death","no death"),times=l)
    })
    
    
}


#' Samples from a mixture model
#'
#' A matrix of 2-dimensional Gaussian mixture samples, the samples came from 4 different Gaussian distributions
#'
#' @docType data
#'
#' @usage data(mmData)
#'
#' @format A matrix of Gaussian samples, each row is one sample.
"mmData"

#' Samples from a hierarchical mixture model
#'
#' A list of 2-dimensional Gaussian mixture samples and the corresponding group labels. The samples are generated by 4 different Gaussian distributions. The samples are separated into 30 groups.
#'
#' @docType data
#'
#' @usage data(mmhData)
#'
#' @format A list of two elements:
#' \describe{
#'   \item{x}{matrix, 2-dimensional Gaussian samples, each row is a sample}
#'   \item{groupLabel}{integer, the group label of each Gaussian sample}
#' }
"mmhData"

#' Samples from a hierarchical mixture model with two layers of hierarchies
#'
#' A list of 2-dimensional Gaussian mixture samples and the corresponding group labels. The samples are generated by 4 different Gaussian distributions. Each sample is assigned to a group and a subgroup. There are 2 groups, group 1 has 10 subgroups, group 2 has 20 subgroups.
#'
#' @docType data
#'
#' @usage data(mmhhData)
#'
#' @format A list of two elements:
#' \describe{
#'   \item{x}{matrix, 2-dimensional Gaussian samples, each row is a sample}
#'   \item{groupLabel}{integer, the group label of each Gaussian sample}
#'   \item{subGroupLabel}{integer, the subgroup label of each Gaussian sample}
#' }
"mmhhData"

#' Samples from a simple linear model
#'
#' A list of two elements, a matrix "X" and a numeric vector "x". They came from a linear model: x = X*0.3 + epsilon, where epsilon is Gaussian distributed with mean 0 and variance 25.
#'
#' @docType data
#'
#' @usage data(lrData)
#'
#' @format A list of two elements:
#' \describe{
#'   \item{x}{numeric, linear samples}
#'   \item{X}{matrix, the "locations" of the linear samples}
#' }
"lrData"

#' @title Samples from a hierarchical linear model
#' @description
#' The data was part of the 2002 Educational Longitudinal Study (ELS), a survey of students from a large sample of schools across the United States. This dataset includes a population of schools as well as a population of students within each school.
#' @docType data
#'
#' @usage data(lrData)
#'
#' @format A list of three elements:
#' \describe{
#'   \item{mathScore}{numeric, the mathScore of each student}
#'   \item{socioeconomicStatus}{numeric, the socioeconomic status score of each student}
#'   \item{schoolID}{integer, the school ID of each student}
#' }
#' @references Hoff, Peter D. A first course in Bayesian statistical methods. Vol. 580. New York: Springer, 2009.
"hlrData"


#' farm ads data
#'
#' A subset of farm ads data from https://archive.ics.uci.edu/ml/datasets/Farm+Ads
#'
#' @docType data
#'
#' @usage data(farmadsData)
#'
#' @format A list of two elements:
#' \describe{
#'   \item{word}{character, the words}
#'   \item{document}{integer, document id of each word}
#' }
#' @source \href{https://archive.ics.uci.edu/ml/datasets/Farm+Ads}{Farm-Ads}
"farmadsData"

#' Cancer mortality of 20 cities
#'
#' Cancer mortality data from Ordinal Data Modeling(1999) p24. This dataset is a list of 20 character vectors, representing the individuals in 20 cities' cancer mortality information. There can be only two possible values "death" and "no death" in each character vector. For example "death" occurs 3 times the 10th character vector, while "no death" occurs 582 times, this mean there are 3 death among the 585 cancer patients in city 10.
#'
#' @docType data
#'
#' @usage data(cancerData)
#'
#' @format A list of 20 character vectors.
#' @references Johnson, Valen E., and James H. Albert. Ordinal data modeling. Springer Science & Business Media, 2006.
"cancerData"
